# shell integration is sourced and configured manually
shell_integration no-rc

# font_family FiraCode Nerd Font
# FiraCode doesn't have italic, bold
font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font:style=ExtraBold

update_check_interval 0
scrollback_lines 20000
enable_audio_bell no
# scrollback_pager = "moor --no-linenumbers"; # todo: INPUT_LINE_NUMBER

